- name: example_value
  path: $.values[*]?(@.state == ACTIVE)
  labels:
    environment: betad
    id: $.id
  type: object
  extractor: 
  help: Example of sub-level value scrapes from a json
  values:
    active: 1
    boolean: $.some_boolean
    count: $.count