---
metrics:
- name: assets
  type: object
  extractor: jq
  help: Get asset metrics
  path: '$. | group_by(.asset) | . as $o | [ keys[] | {"asset": ($o[.][0].asset|tostring), "kms": [$o[.][].period_km] | add, "status": $o[.]|last .status}]'
  labels:
    asset: $.asset
    status: $.status
  values:
    kms: $.kms
